/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 
package student_attendance_control_system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.text.Document;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JFileChooser;

/**
 *
 * @author acer
 */
public class Report_Generating extends javax.swing.JFrame {

    public Report_Generating() {
        initComponents();
    }
    // for attendance report generating
    public ArrayList<Attendance>attendanceList(){
    
        ArrayList<Attendance>attendent_list = new ArrayList<>();
        
        try{
            ConnectionDB c = new ConnectionDB();
            Statement stmt =c.getConnectionDB().createStatement();
            String Stu_id=Stu_Id.getText();
            String query="SELECT FName,LName,NIC,Date FROM attendance WHERE SID='"+Stu_id+"'" ;
            ResultSet rs= stmt.executeQuery(query);
            
            while(rs.next()){
            Attendance attendance= new Attendance(rs.getString("FName"),rs.getString("LName"),rs.getString("NIC"),rs.getDate("Date"));
            attendent_list.add(attendance);
            
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
        return attendent_list;
    }
    
     public void show_attendentlist(){
    ArrayList<Attendance> list= attendanceList();
        DefaultTableModel model=(DefaultTableModel)attendance_table.getModel();
        Object[] row = new Object[4];
        
        for(int i=0;i<list.size();i++){
            
            row[0]=list.get(i).getFname();
            row[1]=list.get(i).getLname();
            row[2]=list.get(i).getNIC();
            row[3]=list.get(i).getDate();
            model.addRow(row);
        }
    }
    
    
    // for Mark's report generating
    public ArrayList<Mark>subjectList(){
        ArrayList<Mark> marklist= new ArrayList<>();
        try{
       ConnectionDB conn=new ConnectionDB();
       
       Statement stmt = conn.getConnectionDB().createStatement();
       
       String mark_subID=SubName.getText();
       
       String query="SELECT MStuId,MpaperNo,MarkObtain FROM mark WHERE MSubject='"+mark_subID+"'";
       
       ResultSet rs= stmt.executeQuery(query);
       while(rs.next()){
       Mark mark = new Mark(rs.getString("MStuId"),rs.getString("MPaperNo"),rs.getString("MarkObtain"));
       marklist.add(mark);
       }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        return marklist;
    }
        
    public void show_mark(){
    ArrayList<Mark> list= subjectList();
        DefaultTableModel model=(DefaultTableModel)marks_table.getModel();
        Object[] row = new Object[3];
        
        for(int i=0;i<list.size();i++){
            
            row[0]=list.get(i).getstuId();
            row[1]=list.get(i).getpaperNum();
            row[2]=list.get(i).getMarksObtaion();
            model.addRow(row);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SubName = new javax.swing.JTextField();
        Subject_Id_search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        marks_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Stu_Id = new javax.swing.JTextField();
        StudentId_search_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        attendance_table = new javax.swing.JTable();
        PDF_Gene_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Report Genarating");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Marks ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText(" Subject");

        Subject_Id_search_btn.setBackground(new java.awt.Color(255, 255, 255));
        Subject_Id_search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Subject_Id_search_btn.setForeground(new java.awt.Color(0, 0, 102));
        Subject_Id_search_btn.setText("Search");
        Subject_Id_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Subject_Id_search_btnActionPerformed(evt);
            }
        });

        marks_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "paper No:", "Marks Obtain"
            }
        ));
        jScrollPane1.setViewportView(marks_table);
        if (marks_table.getColumnModel().getColumnCount() > 0) {
            marks_table.getColumnModel().getColumn(0).setResizable(false);
            marks_table.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Save to PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SubName, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Subject_Id_search_btn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Subject_Id_search_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Attendance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 0, 102))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Student ID");

        StudentId_search_btn.setBackground(new java.awt.Color(255, 255, 255));
        StudentId_search_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        StudentId_search_btn.setForeground(new java.awt.Color(0, 0, 102));
        StudentId_search_btn.setText("Search");
        StudentId_search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentId_search_btnActionPerformed(evt);
            }
        });

        attendance_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First name", "Last name", "NIC", "Date"
            }
        ));
        jScrollPane2.setViewportView(attendance_table);

        PDF_Gene_Btn.setText("Generate PDF");
        PDF_Gene_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDF_Gene_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stu_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(StudentId_search_btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(PDF_Gene_Btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Stu_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentId_search_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(PDF_Gene_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(238, 238, 238))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Subject_Id_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Subject_Id_search_btnActionPerformed
        show_mark();
    }//GEN-LAST:event_Subject_Id_search_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
    
        
        
        try {
            
            Document doc=new Document();
            try {
                
                File f=new File("Report2.pdf");
                if(!f.exists()){
                    try {
                        f.createNewFile();
                    } catch (IOException ex) {
                        Logger.getLogger(Report_Generating.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                
                PdfWriter.getInstance(doc,new FileOutputStream(f));
            } catch (DocumentException ex) {
                Logger.getLogger(Report_Generating.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            
             doc.add(new Paragraph("Student ID"+"   |   "+"Paper No"+"   |    "+"Marks Obtain"));
            try {
                
                
                for (int i = 0; i < marks_table.getSelectedRowCount(); i++) {
                    
                    doc.add(new Paragraph(marks_table.getValueAt(i, 0).toString()+"                    "+marks_table.getValueAt(i, 1).toString()+"                      "+marks_table.getValueAt(i, 2).toString()));
               
                
                }
                
                
            } catch (DocumentException ex) {
                Logger.getLogger(Report_Generating.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Report_Generating.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Report_Generating.class.getName()).log(Level.SEVERE, null, ex);
        }
    
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PDF_Gene_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDF_Gene_BtnActionPerformed
     Document doc= new Document();
     try{
     String path="";
     String Stu_id=Stu_Id.getText();
     JFileChooser j= new JFileChooser();
     j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
     int x=j.showSaveDialog(this);
     
     if(x==JFileChooser.APPROVE_OPTION){
         path=j.getSelectedFile().getPath();
      
     }
     
     PdfWriter.getInstance(doc,new FileOutputStream(path+Stu_id+".pdf"));
     
     doc.open();
         doc.add(new Paragraph("Attendance Report                "));
         
         PdfPTable tbl= new PdfPTable(4);
         
         //Adding headers
         tbl.addCell("First name");
         tbl.addCell("Last name");
         tbl.addCell("NIC");
         tbl.addCell("Date");
         
         for(int i =0; i< attendance_table.getRowCount();i++){
             String Fname=attendance_table.getValueAt(i, 0).toString();
             String Lname=attendance_table.getValueAt(i, 1).toString();
             String NIC=attendance_table.getValueAt(i, 2).toString();
             String date=attendance_table.getValueAt(i, 3).toString();
             tbl.addCell(Fname);
             tbl.addCell(Lname);
             tbl.addCell(NIC);
             tbl.addCell(date);
         
         }
         doc.add(tbl);
         JOptionPane.showMessageDialog(this,"Successfully Created");
         
         
     }catch(Exception e){
         JOptionPane.showMessageDialog(rootPane, e.getMessage());
     
     } 
     doc.close();
    }//GEN-LAST:event_PDF_Gene_BtnActionPerformed

    private void StudentId_search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentId_search_btnActionPerformed
       show_attendentlist();
    }//GEN-LAST:event_StudentId_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Generating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Generating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Generating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Generating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Generating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PDF_Gene_Btn;
    private javax.swing.JTextField Stu_Id;
    private javax.swing.JButton StudentId_search_btn;
    private javax.swing.JTextField SubName;
    private javax.swing.JButton Subject_Id_search_btn;
    private javax.swing.JTable attendance_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable marks_table;
    // End of variables declaration//GEN-END:variables
}
